apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-crawler-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-crawler-api
  template:
    metadata:
      labels:
        app: web-crawler-api
    spec:
      containers:
      - name: web-crawler-api
        image: elasticmofos/web-crawler:0.2.0
        env:
        - name: CONTAINER_TYPE
          value: api
        envFrom:
          - secretRef:
              name: web-crawler-secret
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: web-crawler-api-service
  labels:
    app: web-crawler-api-service
spec:
  ports:
  - port: 8000
    name: http
    targetPort: 8000
  selector:
    app: web-crawler-api
