apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-crawler-flower-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-crawler-flower
  template:
    metadata:
      labels:
        app: web-crawler-flower
    spec:
      containers:
      - name: web-crawler-flower
        image: elasticmofos/web-crawler:0.1.1
        env:
        - name: CONTAINER_TYPE
          value: flower
        envFrom:
          - secretRef:
              name: web-crawler-secret
        ports:
        - containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: web-crawler-flower-service
  labels:
    app: web-crawler-flower-service
spec:
  ports:
  - port: 5555
    name: http
    targetPort: 5555
  selector:
    app: web-crawler-flower
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-crawler-ingress
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /tasks
        pathType: Prefix
        backend:
          service:
            name: web-crawler-flower-service
            port:
              number: 5555
      - path: /broker
        pathType: Prefix
        backend:
          service:
            name: web-crawler-flower-service
            port:
              number: 5555
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: web-crawler-flower-service
            port:
              number: 5555
      - path: /worker
        pathType: Prefix
        backend:
          service:
            name: web-crawler-flower-service
            port:
              number: 5555
