apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-crawler-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-crawler-worker
  template:
    metadata:
      labels:
        app: web-crawler-worker
    spec:
      containers:
      - name: web-crawler-worker
        image: elasticmofos/web-crawler:0.1.1
        env:
        - name: CONTAINER_TYPE
          value: worker
        envFrom:
          - secretRef:
              name: web-crawler-secret
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: web-crawler-worker-service
  labels:
    app: web-crawler-worker-service
spec:
  ports:
  - port: 8001
    name: http
    targetPort: 8000
  selector:
    app: web-crawler-worker